apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: customer-statestore  # Used in your service code to reference this store
  namespace: default
spec:
  type: state.sqlserver
  version: v1
  metadata:
  - name: connectionString
    value: "Server=tcp:your-server.database.windows.net,1433;Initial Catalog=CustomerDB;Persist Security Info=False;User ID=your-user;Password=your-password;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
  - name: tableName
    value: "CustomersState"  # Table that will be automatically created
  - name: keyType
    value: "string"         # Type of your key (e.g., GUID string)
  - name: keyLength
    value: "200"            # Max length of key column
  - name: schema
    value: "dbo"            # Database schema to use
  - name: indexedProperties
    value: "email,status"   # Optional columns to index for querying
  - name: metadataTableName
    value: "CustomersMetadata" # Optional table for additional metadata